FROM jenkins/jenkins:lts-jdk17
USER root
# Docker CLI + plugin compose (hablan con el Docker del host por el socket)
COPY --from=docker:27-cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker:27-cli /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
USER jenkins
RUN jenkins-plugin-cli --plugins git workflow-aggregator github
